# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Arbeiten mit Python und Jupyter Notebooks
author: Matthias Baitsch
# logo: logo.png
number_toc_chapters: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: arbeiten-mit-python.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/matthiasbaitsch/python_numerik_quickstart
  path_to_book: 01-skript
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
#  use_issues_button: true
#  use_repository_button: true
